FROM rust:latest

ARG MLS_LISTINGS_URL
ARG MK_REALESTATE_LISTINGS_API_TOKEN
ARG MK_REALESTATE_LISTINGS_API_URL

ENV MLS_LISTINGS_URL=$MLS_LISTINGS_URL
ENV MK_REALESTATE_LISTINGS_API_TOKEN=$MK_REALESTATE_LISTINGS_API_TOKEN
ENV MK_REALESTATE_LISTINGS_API_URL=$MK_REALESTATE_LISTINGS_API_URL

WORKDIR /usr/src/app

COPY . .

RUN cargo build --release --bin mk-realestate

ENTRYPOINT ["/usr/src/app/target/release/mk-realestate"]
