name: Build and Push Docker Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MLS_LISTINGS_URL: ${{ secrets.MLS_LISTINGS_URL }}
      MK_REALESTATE_LISTINGS_API_TOKEN: ${{ secrets.MK_REALESTATE_LISTINGS_API_TOKEN }}
      MK_REALESTATE_LISTINGS_API_URL: ${{ secrets.MK_REALESTATE_LISTINGS_API_URL }}
      RUST_LOG: ${{ vars.RUST_LOG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/scripts:latest

      - name: Run container
        run: docker run ${{ secrets.DOCKER_USERNAME }}/scripts:latest
